[package]
authors = ["The Cloud Hypervisor Authors"]
edition.workspace = true
name = "tracer"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
libc = { workspace = true, optional = true }
log = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive", "rc"], optional = true }
serde_json = { workspace = true, optional = true }

[features]
tracing = ["dep:libc", "dep:log", "dep:serde", "dep:serde_json"]

[lints]
workspace = true
