load("@rules_rust//rust:defs.bzl", "rust_library")

package(
    default_visibility = ["//visibility:public"],
)

rust_library(
    name = "option_parser",
    srcs = glob(["src/*.rs"]),
    visibility = ["//visibility:public"],
)